repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Ensure commit messages use Conventional Commits formatting;
  # cf. .cz.toml.
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 55d62f82df48e68346132837311d6103617a4e69  # frozen: v4.16.5
    hooks:
      - id: commitizen

  # Check shell scripts, limiting output to errors and warnings.
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: 99470f5e12208ff0fb17ab81c3c494f7620a1d8d  # frozen: v0.11.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]

  # Check GitHub Actions workflows.
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
    hooks:
      - id: actionlint

  # Check third-party actions' pins.
  - repo: local
    hooks:
      - id: pinact
        name: Third-party actions
        language: unsupported
        entry: pinact run -u --min-age 7
        pass_filenames: false
