#!/usr/bin/env bash
set -Eeuo pipefail
shopt -s nullglob

# Explicitly operate in same directory as this script.
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

# This uses data collected by the version tracker.
if [ ! -f versions.json ]; then
    echo Run \"versions.sh\" first.
    exit 1
fi

# Install bashbrew's gawk-based templating engine.
jqt=".jq-template.awk"
if [ -n "${BASHBREW_SCRIPTS:-}" ]; then
    jqt="${BASHBREW_SCRIPTS}/jq-template.awk"
elif [ "${BASH_SOURCE[0]}" -nt "${jqt}" ]; then
    # https://github.com/docker-library/bashbrew/blob/master/scripts/jq-template.awk
    curl -sLo "${jqt}" https://github.com/docker-library/bashbrew/raw/9f6a35772ac863a0241f147c820354e4008edf38/scripts/jq-template.awk
fi

# Use this notice in templates.
function warn_against_edits() {
    cat <<EOH
#
# NOTE: DO NOT EDIT THIS FILE DIRECTLY.
#
# This file is generated by "apply-templates.sh".  It will overwrite
# any changes the next time it runs.
#

EOH
}

# Process the specified versions (defaults to all tracked versions).
if [ "$#" -eq 0 ]; then
    versions="$(jq -r 'keys | map(@sh) | join(" ")' versions.json)"
    eval "set -- ${versions}"
fi
for version; do
    export version
    echo -n "Processing ${version}..."

    # Reset the container image definition for this version.
    rm -rf "${version:?}/"

    # Generate the container image definition.
    mkdir -p "${version}"
    {
        warn_against_edits
        gawk -f "${jqt}" Dockerfile.template
    } > "${version}/Dockerfile"
    {
        cat <<EOH
#!/usr/bin/env bash
EOH
        warn_against_edits
        gawk -f "${jqt}" docker-entrypoint.sh.template
    } > "${version}/docker-entrypoint.sh"
    cp -a config.py "${version}/"
    echo " done."
done
