#!/usr/bin/env bash
# shellcheck disable=SC2206
# shellcheck disable=SC2046
set -Eeuo pipefail
shopt -s nullglob

# This controls additional aliases to add to the tags
# The `latest` tag is provided as a convenience.  However, deployers
# should pin to the desired version tag or image hash as appropriate;
# cf. https://vsupalov.com/docker-latest-tag/.
# declare -A aliases=(
#    [2.0]='2 latest'
#    [1.0]='1'
# )

# Explicitly operate in same directory as this script.
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
self="$(basename "${BASH_SOURCE[0]}")"

# Process the specified versions (defaults to all tracked releases).
if [ "$#" -eq 0 ]; then
    versions="$(jq -r 'keys | map(@sh) | join(" ")' versions.json)"
    eval "set -- $versions"
fi

# Sort version numbers by newest first.
IFS=$'\n'; set -- $(sort -rV <<<"$*"); unset IFS

# Get the most recent commit that modified any of "$@".
file_commit() {
    git log -1 --format='format:%H' HEAD -- "$@"
}

# Get the most recent commit that modified "$1/Dockerfile" or any file
# COPY'd from "$1/Dockerfile".
dir_commit() {
    local dir="$1"; shift
    (
        cd "$dir"
        files="$(git show HEAD:./Dockerfile | awk '
            toupper($1) == "COPY" {
                for (i = 2; i < NF; i++) {
                    if ($i ~ /^--from=/) {
                        next
                    }
                    print $i
                }
            }
        ')"
        file_commit Dockerfile $files
    )
}

# Output the library entry header.
cat <<EOH
# This file was generated by {{ cookiecutter.repo_url }}/blob/$(file_commit "$self")/$self.

Maintainers: REPLACEME <REPLACEME@researchdata.us> (@)
GitRepo: {{ cookiecutter.repo_url }}.git
GitFetch: refs/heads/main
Builder: buildkit
EOH

# Prints "$2$1$3$1...$N".
join() {
    local sep="$1"; shift
    local out; printf -v out "${sep//%/%%}%s" "$@"
    echo "${out#$sep}"
}

# Output library entries for each tracked version.
for version; do
    export version
    full_version="$(
        jq -r '
            .[env.version].version | select(.)
        ' versions.json
    )"
    version_aliases=(
        $full_version
        $version
        ${aliases[$version]:-}
    )
    dir="${version}"

    # Pin to the most recent commit that altered this folder.
    commit="$(dir_commit "${dir}")"

    # To keep things simple, build images for just two hardware
    # architectures.
    echo
    cat <<-EOE
Tags: $(join ', ' "${version_aliases[@]}")
Architectures: amd64, arm64v8
GitCommit: ${commit}
Directory: ${dir}
EOE
done
