[tool.commitizen]
bump_message = "bump: release version $new_version"
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver2"
version = "1.0.0"
update_changelog_on_bump = true

[tool.commitizen.change_type_map]
build = "Build System"
chore = "Miscellaneous"
ci = "CI/CD Workflow"
docs = "Documentation"
feat = "New Features"
fix = "Bug Fixes"
perf = "Performance Improvements"
refactor = "Refactoring"
style = "Style"
test = "Testing"
