---
name: Continuous Integration

# Trigger this workflow manually, by pushing commits to any branch, or
# by filing a pull request.
on:
  workflow_dispatch:
  push:
  pull_request:

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ResearchDataCom/actions/pre-commit@e090df9783f33a74a04ffd6ba047901aba70b6d8 # v2.1.2
        with:
          access-app-id: ${{ vars.PRIVATE_REPOSITORY_ACCESS_APP_ID }}
          access-key: ${{ secrets.PRIVATE_REPOSITORY_ACCESS_KEY }}
      - uses: ResearchDataCom/actions/opentofu-freeze@e090df9783f33a74a04ffd6ba047901aba70b6d8 # v2.1.2

  release:
    # Prevent race conditions of more than one release job in case of
    # multiple pushes to the main branch in a short period of time.
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: false
    needs:
      - lint
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: ResearchDataCom/actions/cz-bump@e090df9783f33a74a04ffd6ba047901aba70b6d8 # v2.1.2
    outputs:
      released: ${{ steps.release.outputs.released }}
      tag: ${{ steps.release.outputs.tag }}

  github:
    needs:
      - release
    if: needs.release.outputs.released
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: ResearchDataCom/actions/publish-github@e090df9783f33a74a04ffd6ba047901aba70b6d8 # v2.1.2
        with:
          artifact-paths: .terraform.lock.hcl
          tag: ${{ needs.release.outputs.tag }}
