# This file is needed to generate the Documentation of nodejs code using sphinx which is a python tool
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
# cf. tool.setuptools.package-dir section below
name = "{{ cookiecutter.package_slug }}"
description = "{{ cookiecutter.project_description }}"
version = "0.0.0"
# cf. https://www.bitecode.dev/p/relieving-your-python-packaging-pain,
# https://devguide.python.org/versions/
requires-python = ">=3.12"
# cf. https://pypi.org/classifiers/
classifiers = [
    "Private :: Do Not Upload",
    "Development Status :: 1 - Planning",
]
# To avoid unnecessary developer overhead, only set version
# constraints to address capability, compatibility, or security
# issues, and avoid pinning specific versions if possible.
dependencies = [
]

[project.optional-dependencies]
dev = [
    "commitizen",
    "pre-commit",

    "myst-parser[linkify,rtd]",
    "pystemmer",
    "rinohtype",
    "sphinx",
    "sphinx-js",
    "sphinx-book-theme",
    "sphinx-intl",
    "sphinx-copybutton",
    "sphinx-design",
    "sphinxcontrib-bibtex",
    "sphinxcontrib-svg2pdfconverter[CairoSVG]",
    "sphobjinv",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.commitizen]
bump_message = "bump: release version $new_version"
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver2"
version_provider = "pep621"
update_changelog_on_bump = true

[tool.commitizen.change_type_map]
build = "Build System"
chore = "Miscellaneous"
ci = "CI/CD Workflow"
docs = "Documentation"
feat = "New Features"
fix = "Bug Fixes"
perf = "Performance Improvements"
refactor = "Refactoring"
style = "Style"
test = "Testing"

